version: 2
jobs:
  docker:
    docker:
    - image: docker
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: Docker login
        command: |
          docker login -u=${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
    - run:
        name: Install essentials
        command: |
          apk add --no-cache --virtual .build-deps make gcc
    - run:
        name: build docker image
        command: |
          make docker-build
    - run:
        name: test of docker image
        command: |
          make docker-test
    - run:
        name: publish docker image
        command: |
          make docker-push
          if [ "$CIRCLE_BRANCH" == "master" ]; then
              docker build -t ${DOCKER_USERNAME}/kafka:latest .;
              docker push ${DOCKER_USERNAME}/kafka:latest;
          fi

  k8s:
    machine:
      image: circleci/classic:201808-01
    steps:
      - checkout
      - run:
          name: install minikube and kubectl
          command: make minikube-install
      - run:
          name: run minikube
          command: make minikube-run
      - run:
          name: run tests
          command: make minikube-test-zk
      - run:
          name: clean resources
          command: make minikube-clean-resources
      - run:
          name: run tests with persistent storage
          command: make minikube-test-persistent

  openshift:
    machine:
      image: circleci/classic:201808-01
    steps:
    - checkout
    - run:
        name: install oc
        command: make oc-install
    - run:
        name: run local openshift cluster
        command: make oc-cluster-run
    - run:
        name: run tests
        command: make oc-test-zk
    - run:
        name: clean resources
        command: make oc-clean-resources
    - run:
        name: run tests with persistent storage
        command: make oc-test-persistent

workflows:
  version: 2
  build:
    jobs:
    - docker:
        filters:
          branches:
            only: master
    - k8s:
        requires:
        - docker
        filters:
          branches:
            only: master
    - openshift:
        requires:
        - k8s
        filters:
          branches:
            only: master
