apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    kafka-name: kafka
    component: kafka
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - port: 9092
    name: server
  - port: 2181
    name: zkclient
  - port: 2888
    name: zkserver
  - port: 3888
    name: zkleader
  clusterIP: None
  selector:
    kafka-name: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    kafka-name: kafka
    component: kafka
  annotations:
        # Use this annotation if you want allocate each pod on different node
        # Note the number of nodes must be upper than REPLICAS parameter.
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": [{
                "labelSelector": {
                  "matchExpressions": [{
                    "key": "kafka-name",
                    "operator": "In",
                    "values": ["${NAME}"]
                  }]
                },
                "topologyKey": "kubernetes.io/hostname"
              }]
            }
          }
spec:
  serviceName: kafka
  replicas: 3
  template:
    metadata:
      labels:
        kafka-name: kafka
        component: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: engapa/kafka:2.12-0.11.0.1
        ports:
        - containerPort: 9092
          name: broker-port
        - containerPort: 2181
          name: zkclient
        - containerPort: 2888
          name: zkserver
        - containerPort: 3888
          name: zkleader
        env:
        - name: KAFKA_REPLICAS
          value: "3"
        - name:  KAFKA_ZK_LOCAL
          value: "false"
        - name:  SERVER_zookeeper_connection
          value: "zk-0.zk:2181"
        - name:  SERVER_zookeeper_connection_timeout_ms
          value: "300000"
        livenessProbe:
          exec:
            command:
            - kafka_server_status.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5